### ISSUE TITLE
Enable Auto builds in DockerHub

### ISSUE THREAD

**Issue by hardikns** [instrumentisto/postfix-docker-image#13]
Hey this is nice work.

Is it possible to enable auto builds in DockerHub for this repo so that any upstream changes triggers a new build?

**Comment by tyranron** [comment]
@hardikns unfortunately, this not is not finished yet and we don't recommend to use it. That's why it's not published on Docker Hub and has no versions updates.

We can't give any ETAs when it will be finished. However, you're free to use as the basis for your own Docker image.
